Major changes and updates to facemapSVD pipeline
datajoint/element-facemap pull request #38
Opened 2024-08-20 21:46 UTC by ttngu207

- Rename SVD component-related table attributes
- Update ingestion to handle FullSVD analysis
- Remove redundant helper functions

2024-08-20 21:53 UTC, MilagrosMarin requested changes

2024-08-20 21:53 UTC, MilagrosMarin commented on element_facemap/facial_behavior_estimation.py
> +            run_facemap_process()
I would suggest to make the function private and rename it to `_run_facemap_process()`.

2024-08-20 21:53 UTC, MilagrosMarin commented on setup.py
> +        "facemap[gui] @ git+https://github.com/datajoint/facemap.git",
Following other elements, such as [`element-deeplabcut` setup](https://github.com/datajoint/element-deeplabcut/blob/main/setup.py), I would move the installation of the GUI to `extras_require` and make it optional.

2024-08-21 04:01 UTC, MilagrosMarin commented on element_facemap/facial_behavior_estimation.py
> +            run_facemap_process()
An example [here](https://github.com/datajoint/element-array-ephys/blob/b510cb8aa5499d3f66adae1aa9a168c25303ac19/element_array_ephys/spike_sorting/si_spike_sorting.py#L208-L224), `_run_sorter()` in `element-array-ephys`.

2024-08-21 14:14 UTC, kushalbakshi reviewed
Looks good to me. If you could update the `run_facemap_process` function based on Milagros' comment above, it will ensure consistency in how we deploy the `memoized_result` functionality across Elements. Otherwise, this is ready to merge.

2024-08-21 15:01 UTC, ttngu207 commented
> Looks good to me. If you could update the `run_facemap_process` function based on Milagros' comment above, it will ensure consistency in how we deploy the `memoized_result` functionality across Elements. Otherwise, this is ready to merge.

@MilagrosMarin @kushalbakshi new commit added to address your comment.
There's one inconsistency in this soft convention we have here, in `element-deeplabcut`, we name the function `do_analyze_videos` (not `_do_analyze_videos`)
I'm fine either way, this is a minor point, it doesn't affect any functionality - it's good to stay consistent

2024-08-21 15:10 UTC, kushalbakshi commented
> > Looks good to me. If you could update the `run_facemap_process` function based on Milagros' comment above, it will ensure consistency in how we deploy the `memoized_result` functionality across Elements. Otherwise, this is ready to merge.
> 
> @MilagrosMarin @kushalbakshi new commit added to address your comment. There's one inconsistency in this soft convention we have here, in `element-deeplabcut`, we name the function `do_analyze_videos` (not `_do_analyze_videos`) I'm fine either way, this is a minor point, it doesn't affect any functionality - it's good to stay consistent

Yes, it's probably a good idea to update that one too. As a general rule, any function within the make should probably follow the private function convention just to discourage its use outside the `make`

2024-08-21 15:10 UTC, kushalbakshi approved these changes

2024-08-21 15:13 UTC, MilagrosMarin approved these changes

2024-08-21 15:13 UTC, merged